### PR TITLE
Feature/add php stan

### PR DESCRIPTION
**Pull request by joncojonathan**
I've added PHPStan composer.json and to scripts and set composer to run the test.  Level is set to 8.  I'm struggling to work out how to set `strict_types = 1` unless it's just part of the PHPStan arguments in composer (still reading the docs for PHPStan).

Hopefully this partially addresses #4 ?

### CODE REVIEW

**Review by vitormattos — CHANGES_REQUESTED** [review]
Merge the master in your branch

**Comment by joncojonathan** [comment]
I'll look to resolve those conflicts and update tomorrow.

**Comment by joncojonathan** [comment]
Hello @vitormattos,

Hopefully that's sorted now?

**Comment by joncojonathan** [comment]
The only conflict now seems to be the composer.lock hash value:

```
<<<<<<< feature/addPHPStan
    "content-hash": "0fc50fc4a4ed3f27c9c9e221277936b6",
=======
    "content-hash": "d0b188a5dd26844a21fca9cc63398c58",
>>>>>>> master
```

My `composer.lock` should be the latest, I believe?

**Comment by joncojonathan** [comment]
Hi @vitormattos.  Is this now ready to merge?  I would think the `composer.lock` file needs to keep the hash as I've submitted it due to the changes in my file.  I can apply the original value from `master` (which resolves the conflict) but I don't think that would be correct for Composer.  Any advice appreciated, thanks in advance.

**Comment by vitormattos** [comment]
Is possible solve the problem reported in CI?

**Comment by joncojonathan** [comment]
Hello, the only remaining problems are what PHPStan has found, which are out of scope for this PR.  Are you happy to approve and merge?

**Pull request merged**
